#!/usr/bin/env bash
# Start the PulseFlow device mirror (ws-scrcpy) on port 3848.
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO="$ROOT/ws-scrcpy"
PORT="${PULSEFLOW_MIRROR_PORT:-3848}"
CONFIG="$ROOT/config.yaml"

cat > "$CONFIG" <<EOF
# PulseFlow device-mirror → ws-scrcpy run config (generated by start.sh)
runGoogTracker: true
runApplTracker: false

server:
  - secure: false
    port: ${PORT}
EOF

if [[ ! -f "$REPO/dist/index.js" ]]; then
  echo "device-mirror: not built yet — running setup…"
  if ! "$ROOT/setup.sh"; then
    echo "device-mirror: setup failed; serving offline stub on :${PORT}" >&2
    exec node "$ROOT/offline-stub.mjs" "$PORT"
  fi
fi

if [[ ! -f "$REPO/dist/index.js" ]]; then
  echo "device-mirror: dist missing; serving offline stub on :${PORT}" >&2
  exec node "$ROOT/offline-stub.mjs" "$PORT"
fi

if [[ ! -d "$REPO/dist/node_modules" ]]; then
  echo "device-mirror: installing runtime deps in dist/…"
  (cd "$REPO/dist" && npm install --omit=dev) || {
    echo "device-mirror: dist deps failed; serving offline stub" >&2
    exec node "$ROOT/offline-stub.mjs" "$PORT"
  }
fi

# Clear stale scrcpy-server on attached devices (port 8886 BindException otherwise).
if command -v adb >/dev/null 2>&1; then
  while read -r serial _; do
    [[ -z "${serial:-}" || "$serial" == "List" ]] && continue
    adb -s "$serial" shell 'pkill -f scrcpy.Server >/dev/null 2>&1 || true' || true
  done < <(adb devices 2>/dev/null | awk 'NR>1 && $2=="device" {print $1}')
fi

export WS_SCRCPY_CONFIG="$CONFIG"
echo "device-mirror: starting ws-scrcpy on :${PORT}"
cd "$REPO/dist"
exec node ./index.js
